services:
  mementomori-helper:
    container_name: mementomori-helper
    ports:
      - "5290:8080"
    build:
      context: .
      dockerfile: MementoMori.WebUI/Dockerfile
      args:
        TARGETARCH: x64
    environment:
      - BUILDPLATFORM=linux
    restart: unless-stopped
    volumes:
      - ./Master:/app/Master
      - ${PWD}/appsettings.user.json:/app/appsettings.user.json:rw
